### ISSUE TITLE
[Feature] PICS v2 Support

### ISSUE THREAD

**Issue by rquidute** [project-chip/certification-tool#290]
### Goals
Get rid of the top-level PICS annotations in the Python TC scripts
Switch to a DUT-driven test case selection/execution for the TH certification workflow
Ensure that a pre-defined subset of the scripts/TCs is always run before and actually gate the execution of all remaining TCs
Support to certification mode where all applicable test case must be executed in the test run execution

### Tasks

- [ ] DB changes to support certification mode and flag collections and suite as mandatory when applicable.
- [ ] Modify the related test execution endpoints in order to support certification mode and make mandatories test cases prioritized
- [ ] Modify python test execution flow to support the certification mode and support to skip not applicable test cases

### Use Cases

NA
